TestBlog/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from . import views
import blog_article.urls
import api.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(blog_article.urls)),
    url(r'^api/', include(api.urls)),
    url(r'^$', views.HomeView.as_view(), name = 'home'),
]

api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^', views.ArticleList.as_view()),
    url(r'^<int:pk>/', views.ArticleDetail.as_view()),
]

blog_article/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/(?P<day>\d{1,2})/(?P<pk>\d+)-(?P<slug>[-\w]*)/$',
        views.ArticlesDetail.as_view(), name='article_detail'),
]

api/models.py
from django.db import models

# Create your models here.

blog_article/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify




# Create your models here.

class Articles (models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    slug = models.SlugField(default='', editable=False)
    author = models.ForeignKey(
        'auth.User',
        related_name='article',
        on_delete=models.CASCADE
    )
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_modified = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "{}".format(self.title, self.body, self.date_created, self.date_modified)

    def get_absolute_url(self):
        kwargs = {'year': self.date_created.year,
                  'month': self.date_created.month,
                  'day': self.date_created.day,
                  'slug': self.slug,
                  'pk': self.pk}
        return reverse('article_detail', kwargs=kwargs)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

class Comment(models.Model):
    article = models.ForeignKey(
        Articles,
        on_delete=models.CASCADE,)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True, editable=False)
    date_modified = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "{}".format(self.article, self.name, self.date_created, self.date_modified, self.body)

blog_article/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

    def __init__(self, *args, **kwargs):
        self.article = kwargs.pop('article')  # the blog entry instance
        super().__init__(*args, **kwargs)


    def save(self):
        comment = super().save(commit=False)
        comment.article = self.article
        comment.save()
        return comment

TestBlog/views.py
from django.views.generic import ListView
from blog_article.models import Articles
from django.shortcuts import render

# Create your views here.

class HomeView(ListView):
    template_name = 'index.html'
    queryset = Articles.objects.order_by('-date_created')

api/views.py
from django.shortcuts import render
from rest_framework import generics

from blog_article.models import Articles
from .serializers import ArticleSerializer
# Create your views here.

class ArticleList(generics.ListAPIView):
    queryset = Articles.objects.all()
    serializer_class = ArticleSerializer


class ArticleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Articles.objects.all()
    serializer_class = ArticleSerializer

blog_article/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from blog_article.models import Articles
# Create your views here.

class ArticlesDetail(DetailView):
    model = Articles

    def get_success_url(self):
        return self.get_object().get_absolute_url()

templates/_article.html
       <article>                                                                      
                                                                                      
           <h2><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h2>  
                                                                                      
           <p class="subheader">                                                      
               <time>{{ article.date_modified|date }}</time>                          
           </p>                                                                       
                                                                                      
           <p></p>                                                                    
                                                                                      
           {{ article.body|linebreaks }}                                              
                                                                                      
       </article>                                                                     

templates/article_detail.html
{% extends "base_page.html" %}

{% block content %}
    {% include "_article.html" with article=article only %}
    <hr>
<h4>Comments</h4>
{% for comment in article.comment_set.all %}
    <p><em>Posted by {{ comment.name }}</em></p>
    {{ comment|linebreaks }}
{% empty %}
    No comments yet.
{% endfor %}
{% endblock %}

templates/articles_detail.html
{% extends "base_page.html" %}

{% block content %}
    {% include "_article.html" with article=article only %}
    <hr>
<h4>Comments</h4>
{% for comment in article.comment_set.all %}
    <p><em>Posted by {{ comment.name }}</em></p>
    {{ comment|linebreaks }}
{% empty %}
    No comments yet.

<form method="post">
     {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Create Comment">
</form>

{% endfor %}
{% endblock %}

templates/base_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Flying circus</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
</head>
<body>
    <section class="row">
        <header class="large-12 columns">
            <h1><h1> Welkome to Peter Python`s Blog!</h1></h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %}
            {% endblock %}
        </div>

        <div class="large-4 columns">
            <h3>About Me</h3>
            <p>I started coding 22 minutes ago.</p>
                <h3>Recent Articles</h3>
                {% article_history %}
        </div>

    </section>

</body>
</html>

templates/blog_article/_article_history.html
<ul>
    {% for article in articles %}
        <li>{{ article.title }}</li>
        {% empty %}
        <li>No recent articles</li>
    {% endfor %}
</ul>

templates/index.html
{% extends "base_page.html" %}

{% block content %}
    {% for article in articles_list %}
        {% include "_article.html" with article=article only %}
    {% empty %}
        <p>No blog entries yet.</p>
    {% endfor %}
{% endblock content %}